/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.steppenwells.droidswarm;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int arrows=0x7f020001;
        public static final int reset=0x7f020002;
        public static final int touch=0x7f020003;
    }
    public static final class id {
        public static final int reset=0x7f060001;
        public static final int swarm=0x7f060000;
        public static final int touch=0x7f060002;
    }
    public static final class layout {
        public static final int droidswarm_layout=0x7f030000;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int menu_reset=0x7f040001;
        public static final int menu_touch=0x7f040002;
    }
}
